#!/bin/sh

# borrowed from https://git.kernel.org/pub/scm/git/git.git/tree/GIT-VERSION-GEN

GVF=$1

VN=$(git describe --match "$2" HEAD 2>/dev/null) &&
	case "$VN" in
	$2*)
		git update-index -q --refresh
		test -z "$(git diff-index --name-only HEAD --)" ||
		VN="$VN-dirty" ;;
	esac

if [ -z "$VN" ]; then
	# no tag, fallback to commit id only
	VN="g$(git rev-parse --short HEAD)"
	test -z "$(git diff-index --name-only HEAD --)" || VN="$VN-dirty"
fi

VN=$(expr "$VN" : v*'\(.*\)')

if test -r $GVF
then
	VC=$(sed -e 's/^GIT_VERSION = //' <$GVF)
else
	VC=unset
fi
test "$VN" = "$VC" || {
	echo >&2 "  GIT_VERSION: $VN"
	echo "GIT_VERSION = $VN" >$GVF
}
