# Comment: ACM-Device driver.

MAKEFLAGS += --no-print-directory

modules:
	@$(MAKE) -C acm $@

modules_install:
	@$(MAKE) -C acm $@

coccicheck:
	@$(MAKE) -C acm $@

clean:
	@$(MAKE) -C acm $@

doc:
	@$(MAKE) -C acm $@

install-doc:
	@$(MAKE) -C acm $@

